spring:
  application:
    name: crew
  jpa:
    database: mysql
    generate-ddl: off
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/explorer?createDatabaseIfNotExist=true
    username: command-center
    password: galaxy
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost